version: "3.9"

services:
  frontend:
    container_name: react-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    restart: unless-stopped
    env_file:
      - ./.env-prod

