name: Deploy on Internal VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync environment
        run: |
          cat > .env-prod << EOF
          VITE_API_URL=${{ secrets.VITE_API_URL }} 
          EOF

      - name: Start with Docker Compose
        run: |
          docker-compose up -d --build
